In [2]:
from google.colab import files
data=files.upload()

Saving fitness_poses_csvs_out_basic.csv to fitness_poses_csvs_out_basic (1).csv

In [46]:
import pandas as pd
data=pd.read_csv('fitness_poses_csvs_out_basic.csv', header=None)

In [47]:
data.head(5)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,11-0.png,poses_image_in,251.16796,139.51116,-57.46616,258.57371,139.43968,-58.43178,259.98703,141.30880,...,10.36762,193.04339,18.42931,37.95127,208.01741,40.17400,-21.64718,220.42846,17.27170,11.70774
1,14-0.png,poses_image_in,180.05377,456.59012,-351.21291,175.45695,432.82032,-333.88760,180.79462,427.51816,...,115.21585,855.89605,548.45213,-13.57002,257.85053,-11.92391,24.55208,934.19334,545.05641,-132.91782
2,15-0.png,poses_image_in,64.76089,185.55149,-167.83225,63.74838,173.75429,-161.38590,66.67155,171.52743,...,27.65646,374.04734,229.55812,-23.61894,121.06483,-5.74977,-13.46041,388.70814,232.22136,-72.74131
3,16-0.png,poses_image_in,285.88044,157.10142,-10.54696,289.74747,154.05328,-21.79637,289.60843,153.43337,...,37.70741,266.66991,90.50619,72.01171,297.49004,-1.93496,7.45418,299.12380,96.57082,38.01575
4,17-0.png,poses_image_in,402.66485,225.24015,-63.55309,412.63665,223.03520,-54.66654,415.10827,225.96813,...,-41.41364,315.06621,38.28531,-17.70360,-14.56932,294.95371,-122.02104,351.17359,34.68625,-70.05679

## ✅ 어깨 좌표 (왼, 오 👉 각각 x,y좌표)

In [87]:
shoulder_df=data.iloc[:,[33,34, 36,37]]
shoulder_df

           33         34         36         37
0   140.80576  -42.52939  173.34304  -37.27213
1   469.73976 -290.34025  402.21393  -47.63913
2   191.79598 -142.61198  161.10053  -31.69501
3   161.01343  -17.68698  149.67238  -61.54688
4   225.86607  -37.98970  283.39523  -17.31365
5   314.21524 -197.25923  283.74144   -0.51895
6   144.51460  -91.68635  196.56404    4.89484
7   403.26572 -502.19217  363.77718 -119.88528
8   201.23498  -56.83050  177.52957   22.42037
9   187.03758  -46.08881  243.89215  -77.74906
10  246.92919 -129.20178  322.37307 -148.70581
11  304.66640 -398.28206  256.86724 -127.92893
12  375.04305 -176.73272  479.86368 -156.77796
13  397.10518   41.04359  491.52392   48.73572
14  328.53949 -180.25202  310.09646   67.74269
15  222.72534 -131.89958  276.58399  -91.36055
16  179.60578 -238.52023  157.77848  -52.83850
17  245.18675 -175.59530  206.70095  -22.55894
18  273.30346 -193.37784  244.74324   47.98889
19  245.91216 -113.85846  308.68658  -90.13879
20  240.28892  -24.57242  289.25623   47.75718
21  172.12668 -328.10086  114.00176  -51.02138
22  122.20689    0.84794  163.46391   25.91463
23  110.90450  -63.74147  137.82833   -9.82806
24  351.46663 -333.27369  310.20947  -78.98746
25  225.45386 -230.41705  198.85798  -61.32705
26  120.32702 -111.39649   98.47690  -15.63497
27  101.80251 -111.28806  137.45204  -29.97316
28  325.27727 -186.76510  289.08022   70.07007
29  189.08341  -27.48060  244.57181  -45.20904
30  180.02417 -122.42316  227.67952  -89.40761
31  375.46803  290.40244  506.89001  207.52853
32  249.31030 -140.18580  307.94253  -82.06588
33  133.31631  -78.50751  183.66855 -145.22321
34  319.83808 -295.56674  278.35347  -70.07883
35  362.17955 -249.64139  311.62205  -67.34847
36  162.24381  -88.48077  151.80216   24.11954
37  186.01036  -41.25507  226.04426   -7.18719
38  219.88875 -248.45985  184.72525 -102.36279

## ✅ 어깨 양쪽 평균 column 생성 (center) 

    이미지 너비 기준 (x좌표)

In [88]:
shoulder_df['total'] = shoulder_df.loc[:,33] + shoulder_df.loc[:,36]
shoulder_df['center'] = shoulder_df['total']/2
shoulder_df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

           33         34         36         37      total      center
0   140.80576  -42.52939  173.34304  -37.27213  314.14880  157.074400
1   469.73976 -290.34025  402.21393  -47.63913  871.95369  435.976845
2   191.79598 -142.61198  161.10053  -31.69501  352.89651  176.448255
3   161.01343  -17.68698  149.67238  -61.54688  310.68581  155.342905
4   225.86607  -37.98970  283.39523  -17.31365  509.26130  254.630650
5   314.21524 -197.25923  283.74144   -0.51895  597.95668  298.978340
6   144.51460  -91.68635  196.56404    4.89484  341.07864  170.539320
7   403.26572 -502.19217  363.77718 -119.88528  767.04290  383.521450
8   201.23498  -56.83050  177.52957   22.42037  378.76455  189.382275
9   187.03758  -46.08881  243.89215  -77.74906  430.92973  215.464865
10  246.92919 -129.20178  322.37307 -148.70581  569.30226  284.651130
11  304.66640 -398.28206  256.86724 -127.92893  561.53364  280.766820
12  375.04305 -176.73272  479.86368 -156.77796  854.90673  427.453365
13  397.10518   41.04359  491.52392   48.73572  888.62910  444.314550
14  328.53949 -180.25202  310.09646   67.74269  638.63595  319.317975
15  222.72534 -131.89958  276.58399  -91.36055  499.30933  249.654665
16  179.60578 -238.52023  157.77848  -52.83850  337.38426  168.692130
17  245.18675 -175.59530  206.70095  -22.55894  451.88770  225.943850
18  273.30346 -193.37784  244.74324   47.98889  518.04670  259.023350
19  245.91216 -113.85846  308.68658  -90.13879  554.59874  277.299370
20  240.28892  -24.57242  289.25623   47.75718  529.54515  264.772575
21  172.12668 -328.10086  114.00176  -51.02138  286.12844  143.064220
22  122.20689    0.84794  163.46391   25.91463  285.67080  142.835400
23  110.90450  -63.74147  137.82833   -9.82806  248.73283  124.366415
24  351.46663 -333.27369  310.20947  -78.98746  661.67610  330.838050
25  225.45386 -230.41705  198.85798  -61.32705  424.31184  212.155920
26  120.32702 -111.39649   98.47690  -15.63497  218.80392  109.401960
27  101.80251 -111.28806  137.45204  -29.97316  239.25455  119.627275
28  325.27727 -186.76510  289.08022   70.07007  614.35749  307.178745
29  189.08341  -27.48060  244.57181  -45.20904  433.65522  216.827610
30  180.02417 -122.42316  227.67952  -89.40761  407.70369  203.851845
31  375.46803  290.40244  506.89001  207.52853  882.35804  441.179020
32  249.31030 -140.18580  307.94253  -82.06588  557.25283  278.626415
33  133.31631  -78.50751  183.66855 -145.22321  316.98486  158.492430
34  319.83808 -295.56674  278.35347  -70.07883  598.19155  299.095775
35  362.17955 -249.64139  311.62205  -67.34847  673.80160  336.900800
36  162.24381  -88.48077  151.80216   24.11954  314.04597  157.022985
37  186.01036  -41.25507  226.04426   -7.18719  412.05462  206.027310
38  219.88875 -248.45985  184.72525 -102.36279  404.61400  202.307000

In [90]:
shoulder_df['left_wrist']=data.loc[:,[45]]
shoulder_df['right_wrist']=data.loc[:,[48]]
shoulder_df
#left_wrist_df=data.loc[:,[45, 46]]
#right_wrist_df=data.loc[:,[48, 49]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,33,34,36,37,total,center,left_wrist,right_wrist
0,140.80576,-42.52939,173.34304,-37.27213,314.14880,157.074400,85.86031,155.21631
1,469.73976,-290.34025,402.21393,-47.63913,871.95369,435.976845,517.01282,172.25393
2,191.79598,-142.61198,161.10053,-31.69501,352.89651,176.448255,212.86001,51.06128
3,161.01343,-17.68698,149.67238,-61.54688,310.68581,155.342905,222.54032,116.80642
4,225.86607,-37.98970,283.39523,-17.31365,509.26130,254.630650,134.63237,248.42783
5,314.21524,-197.25923,283.74144,-0.51895,597.95668,298.978340,367.21917,92.51636
6,144.51460,-91.68635,196.56404,4.89484,341.07864,170.539320,121.32825,156.12136
7,403.26572,-502.19217,363.77718,-119.88528,767.04290,383.521450,474.98704,91.07867
8,201.23498,-56.83050,177.52957,22.42037,378.76455,189.382275,251.48467,57.05399
9,187.03758,-46.08881,243.89215,-77.74906,430.92973,215.464865,126.57550,213.45503
10,246.92919,-129.20178,322.37307,-148.70581,569.30226,284.651130,164.86504,251.49273
11,304.66640,-398.28206,256.86724,-127.92893,561.53364,280.766820,342.98882,71.53137
12,375.04305,-176.73272,479.86368,-156.77796,854.90673,427.453365,218.06677,403.03582
13,397.10518,41.04359,491.52392,48.73572,888.62910,444.314550,256.16480,394.64102
14,328.53949,-180.25202,310.09646,67.74269,638.63595,319.317975,385.83175,103.09858
15,222.72534,-131.89958,276.58399,-91.36055,499.30933,249.654665,125.45931,249.02664
16,179.60578,-238.52023,157.77848,-52.83850,337.38426,168.692130,241.62606,123.33145
17,245.18675,-175.59530,206.70095,-22.55894,451.88770,225.943850,273.53825,58.54240
18,273.30346,-193.37784,244.74324,47.98889,518.04670,259.023350,316.16789,76.18787
19,245.91216,-113.85846,308.68658,-90.13879,554.59874,277.299370,140.34728,256.96421
20,240.28892,-24.57242,289.25623,47.75718,529.54515,264.772575,152.78276,256.15191
21,172.12668,-328.10086,114.00176,-51.02138,286.12844,143.064220,302.89084,55.27400
22,122.20689,0.84794,163.46391,25.91463,285.67080,142.835400,78.59049,89.72642
23,110.90450,-63.74147,137.82833,-9.82806,248.73283,124.366415,47.25884,128.26078
24,351.46663,-333.27369,310.20947,-78.98746,661.67610,330.838050,438.96217,85.78917
25,225.45386,-230.41705,198.85798,-61.32705,424.31184,212.155920,262.56481,65.49823
26,120.32702,-111.39649,98.47690,-15.63497,218.80392,109.401960,152.05984,66.33070
27,101.80251,-111.28806,137.45204,-29.97316,239.25455,119.627275,89.89142,98.00329
28,325.27727,-186.76510,289.08022,70.07007,614.35749,307.178745,370.20673,91.02656
29,189.08341,-27.48060,244.57181,-45.20904,433.65522,216.827610,120.88739,214.87748
30,180.02417,-122.42316,227.67952,-89.40761,407.70369,203.851845,102.92193,231.22883
31,375.46803,290.40244,506.89001,207.52853,882.35804,441.179020,261.17472,483.26758
32,249.31030,-140.18580,307.94253,-82.06588,557.25283,278.626415,146.64252,257.86816
33,133.31631,-78.50751,183.66855,-145.22321,316.98486,158.492430,119.69135,74.54174
34,319.83808,-295.56674,278.35347,-70.07883,598.19155,299.095775,355.36623,87.08323
35,362.17955,-249.64139,311.62205,-67.34847,673.80160,336.900800,404.84144,113.58426
36,162.24381,-88.48077,151.80216,24.11954,314.04597,157.022985,184.13913,47.60052
37,186.01036,-41.25507,226.04426,-7.18719,412.05462,206.027310,103.79556,201.60801
38,219.88875,-248.45985,184.72525,-102.36279,404.61400,202.307000,274.50556,128.81103

In [74]:
len(data.index)

39

# ✅ 왼쪽, 오른쪽 손목 & 어깨 center 비교

    left result  = True 면 왼쪽으로 누운 상태
    right result = True 면 오른쪽으로 누운 상태

In [94]:
shoulder_df['left_result'] = shoulder_df['center'] > shoulder_df['left_wrist']
shoulder_df['right_result'] = shoulder_df['center'] < shoulder_df['right_wrist']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [95]:
shoulder_df

,33,34,36,37,total,center,left_wrist,right_wrist,left_result,right_result
0,140.80576,-42.52939,173.34304,-37.27213,314.14880,157.074400,85.86031,155.21631,True,False
1,469.73976,-290.34025,402.21393,-47.63913,871.95369,435.976845,517.01282,172.25393,False,False
2,191.79598,-142.61198,161.10053,-31.69501,352.89651,176.448255,212.86001,51.06128,False,False
3,161.01343,-17.68698,149.67238,-61.54688,310.68581,155.342905,222.54032,116.80642,False,False
4,225.86607,-37.98970,283.39523,-17.31365,509.26130,254.630650,134.63237,248.42783,True,False
5,314.21524,-197.25923,283.74144,-0.51895,597.95668,298.978340,367.21917,92.51636,False,False
6,144.51460,-91.68635,196.56404,4.89484,341.07864,170.539320,121.32825,156.12136,True,False
7,403.26572,-502.19217,363.77718,-119.88528,767.04290,383.521450,474.98704,91.07867,False,False
8,201.23498,-56.83050,177.52957,22.42037,378.76455,189.382275,251.48467,57.05399,False,False
9,187.03758,-46.08881,243.89215,-77.74906,430.92973,215.464865,126.57550,213.45503,True,False
10,246.92919,-129.20178,322.37307,-148.70581,569.30226,284.651130,164.86504,251.49273,True,False
11,304.66640,-398.28206,256.86724,-127.92893,561.53364,280.766820,342.98882,71.53137,False,False
12,375.04305,-176.73272,479.86368,-156.77796,854.90673,427.453365,218.06677,403.03582,True,False
13,397.10518,41.04359,491.52392,48.73572,888.62910,444.314550,256.16480,394.64102,True,False
14,328.53949,-180.25202,310.09646,67.74269,638.63595,319.317975,385.83175,103.09858,False,False
15,222.72534,-131.89958,276.58399,-91.36055,499.30933,249.654665,125.45931,249.02664,True,False
16,179.60578,-238.52023,157.77848,-52.83850,337.38426,168.692130,241.62606,123.33145,False,False
17,245.18675,-175.59530,206.70095,-22.55894,451.88770,225.943850,273.53825,58.54240,False,False
18,273.30346,-193.37784,244.74324,47.98889,518.04670,259.023350,316.16789,76.18787,False,False
19,245.91216,-113.85846,308.68658,-90.13879,554.59874,277.299370,140.34728,256.96421,True,False
20,240.28892,-24.57242,289.25623,47.75718,529.54515,264.772575,152.78276,256.15191,True,False
21,172.12668,-328.10086,114.00176,-51.02138,286.12844,143.064220,302.89084,55.27400,False,False
22,122.20689,0.84794,163.46391,25.91463,285.67080,142.835400,78.59049,89.72642,True,False
23,110.90450,-63.74147,137.82833,-9.82806,248.73283,124.366415,47.25884,128.26078,True,True
24,351.46663,-333.27369,310.20947,-78.98746,661.67610,330.838050,438.96217,85.78917,False,False
25,225.45386,-230.41705,198.85798,-61.32705,424.31184,212.155920,262.56481,65.49823,False,False
26,120.32702,-111.39649,98.47690,-15.63497,218.80392,109.401960,152.05984,66.33070,False,False
27,101.80251,-111.28806,137.45204,-29.97316,239.25455,119.627275,89.89142,98.00329,True,False
28,325.27727,-186.76510,289.08022,70.07007,614.35749,307.178745,370.20673,91.02656,False,False
29,189.08341,-27.48060,244.57181,-45.20904,433.65522,216.827610,120.88739,214.87748,True,False
30,180.02417,-122.42316,227.67952,-89.40761,407.70369,203.851845,102.92193,231.22883,True,True
31,375.46803,290.40244,506.89001,207.52853,882.35804,441.179020,261.17472,483.26758,True,True
32,249.31030,-140.18580,307.94253,-82.06588,557.25283,278.626415,146.64252,257.86816,True,False
33,133.31631,-78.50751,183.66855,-145.22321,316.98486,158.492430,119.69135,74.54174,True,False
34,319.83808,-295.56674,278.35347,-70.07883,598.19155,299.095775,355.36623,87.08323,False,False
35,362.17955,-249.64139,311.62205,-67.34847,673.80160,336.900800,404.84144,113.58426,False,False
36,162.24381,-88.48077,151.80216,24.11954,314.04597,157.022985,184.13913,47.60052,False,False
37,186.01036,-41.25507,226.04426,-7.18719,412.05462,206.027310,103.79556,201.60801,True,False
38,219.88875,-248.45985,184.72525,-102.36279,404.61400,202.307000,274.50556,128.81103,False,False

In [ ]:
first_data  = [i for i in range(10, 20)]
second_data = 15

df = pd.DataFrame({'first': first_data, 
                   'second': second_data})

df['result'] = df['first'] > df['second']

print(df)

In [ ]:
df['diff'] = df.num.diff()
df